name: ayus
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # cupertino_icons: ^1.0.2

  http: ^0.13.4
  intl: ^0.17.0
  flutter_switch: ^0.3.2
  google_fonts: ^2.1.0
  progress_loading_button: ^1.1.2
  bot_toast: ^4.0.1
  get: 4.3.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.1
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_app_name:
  name: "Ayus"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/App-Logo-square.png"

flutter_native_splash:
  color: "#f1f7ff"
  image: assets/images/App-Logo-circle.png
  android: true
  ios: true
  web: false
